List alphabets = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'];

List contact_item_list = [
  {
    'first_name': 'Isace',
    'last_name': 'Rowe',
    'image': 'images/sark.jpeg',
    'group': "24",
    'email': 'isacerowe@gamil.com',
    'mobile': '+233 24 783 3330',
    'location': "Kumasi",
  },
  {
    'first_name': 'Smith',
    'last_name': 'Acturey',
    'image': 'images/img3.jpeg',
    'group': "GTL",
    'email': 'smith@gamil.com',
    'mobile': "+233 20 211 8453",
    'location': "Accra",
  },
  {
    'first_name': 'Ashbel',
    'last_name': 'David',
    'image': 'images/kidi.jpeg',
    'group': "Rehoboth",
    'email': 'ashbel@gamil.com',
    'mobile': '+233 24 446 1380',
    'location': "Dansoman",
  },
  {
    'first_name': 'Abish',
    'last_name': 'Glory',
    'image': 'images/img1.jpeg',
    'group': "Aposa",
    'email': 'abish@gamil.com',
    'mobile': "+233 23 540 7432",
    'location': "Accra",
  },
  {
    'first_name': 'Chartty',
    'last_name': 'Love',
    'image': 'images/kwesi.jpeg',
    'group': "Rehoboth",
    'email': 'chartty@gamil.com',
    'mobile': '+233 24 110 1340',
    'location': "Dansoman",
  },
  {
    'first_name': 'Bernny',
    'last_name': 'Hinn',
    'image': 'images/joe.jpeg',
    'group': "Aposa",
    'email': 'hinnbeny@gamil.com',
    'mobile': "+233 20 440 2234",
    'location': "Kasoa",
  },
  {
    'first_name': 'Cira',
    'last_name': 'Wordpowse',
    'image': 'images/img2.jpeg',
    'group': "Apass",
    'email': 'derciraa@gamil.com',
    'mobile': "+233 27 080 2381",
    'location': "Kasoa",
  },
];
